--------------------------------------------------------
--  File created - Wednesday-January-25-2017   
--------------------------------------------------------
DROP VIEW "OPEN_CLOSED_REQUESTS";
DROP VIEW "SME_ASSIGNED_REPORT";
DROP VIEW "VIEW_CURRENT_REQUESTS_TASKS";
--------------------------------------------------------
--  DDL for View OPEN_CLOSED_REQUESTS
--------------------------------------------------------

  CREATE OR REPLACE VIEW "OPEN_CLOSED_REQUESTS" ("DATE_DAY", "OPENED_REQS", "CLOSED_REQS") AS SELECT 
  (CASE WHEN DRT_REQUEST_DATE IS NULL THEN CLOSED_DATE ELSE DRT_REQUEST_DATE END) AS DATE_DAY, 
  COALESCE(CNT1, 0) AS OPENED_REQS, 
  COALESCE(CNT2, 0) AS CLOSED_REQS 
FROM 
  (SELECT 
    TO_DATE(TO_CHAR(DRT_REQUEST_DATE, 'DD-MM-YYYY'), 'DD-MM-YYYY') AS DRT_REQUEST_DATE, 
    COUNT(REQUEST_NUMBER) CNT1 
  FROM DRTS_HISTORY 
    WHERE DRT_REQUEST_DATE > sysdate-30 
    GROUP BY TO_DATE(TO_CHAR(DRT_REQUEST_DATE, 'DD-MM-YYYY'), 'DD-MM-YYYY')) A 
  FULL OUTER JOIN 
    (SELECT 
      TO_DATE(TO_CHAR(CLOSED_DATE, 'DD-MM-YYYY'), 'DD-MM-YYYY') AS CLOSED_DATE, 
      COUNT(REQUEST_NUMBER) CNT2 
    FROM DRTS_HISTORY 
      WHERE CLOSED_DATE > sysdate-30 
      GROUP BY TO_DATE(TO_CHAR(CLOSED_DATE, 'DD-MM-YYYY'), 'DD-MM-YYYY')) B 
  ON DRT_REQUEST_DATE = CLOSED_DATE;
--------------------------------------------------------
--  DDL for View SME_ASSIGNED_REPORT
--------------------------------------------------------

  CREATE OR REPLACE VIEW "SME_ASSIGNED_REPORT" ("SME", "SMECNT", "VALSMECNT") AS select (CASE WHEN as1 IS NULL THEN as2 ELSE as1 END) as SME, coalesce(SMECNT,0) as SMECNT, coalesce(VALSMECNT,0) as VALSMECNT from (
(select assignee as1, count(request_number) as VALSMECNT from drts_history where assignee = validation_sme group by assignee) A 
full outer join 
(select assignee as2, count(request_number) as SMECNT from drts_history where assignee = sme group by assignee) B 
on as1 = as2);
--------------------------------------------------------
--  DDL for View VIEW_CURRENT_REQUESTS_TASKS
--------------------------------------------------------

  CREATE OR REPLACE VIEW "VIEW_CURRENT_REQUESTS_TASKS" ("REQUEST_NUMBER", "DRT_REQUEST_DATE", "PROC_INST_ID_", "CANDIDATE_GROUP", "ASSIGNEE", "REQUEST_TYPE", "REQUEST_STATUS", "CREATED_BY", "ITERATION", "REQUESTED_DUE_DATE", "URGENCY_FLAG", "RELATED_REQUEST_NUMBERS", "TOPIC_KEYWORDS", "REQUESTOR_NAME", "REQUESTOR_ORG", "REQUESTOR_PHONE", "REQUESTOR_EMAIL", "RECEIVER", "RECEIVER_EMAIL", "SME", "SME_ASSIGNED_DATE", "RESOLVED_DATE", "REQUEST_DISPLAY_ID", "VALIDATION_SME", "ASSIGNED_TO_VALIDATOR", "VALIDATION_DATE", "CLOSED_DATE", "MODIFIED_DATE", "PII_FLAG", "REQUEST_PURPOSE", "SPEC_CONSIDERATIONS", "REQUEST_DESCR", "COMMENTS", "TRACKING_SUFFIX", "TRACKING_NUMBER", "SYSTEM_NAME", "DELAY_REASON", "ORIGINAL_REQUEST_DATE", "AGREED_DUE_DATE", "ANTICIPATED_DUE_DATE", "DATE_RUN", "REPORT_TYPE", "QUERY_REPORT_NAME", "CLARIF_ASSUMPS", "DETAIL_STEPS", "VALIDATION_DESCR", "VALIDATION_RESULT", "GOLDEN_QUERY_LIBRARY", "BUSINESS_REQS", "TIER", "SME_GROUP", "VALIDATION_SME_GROUP", "CURRENT_TASK_ID", "CURRENT_TASK_NAME", "CURRENT_TASK_FORM_KEY") AS SELECT DH."REQUEST_NUMBER",DH."DRT_REQUEST_DATE",DH."PROC_INST_ID_",DH."CANDIDATE_GROUP",DH."ASSIGNEE",DH."REQUEST_TYPE",DH."REQUEST_STATUS",DH."CREATED_BY",DH."ITERATION",DH."REQUESTED_DUE_DATE",DH."URGENCY_FLAG",DH."RELATED_REQUEST_NUMBERS",DH."TOPIC_KEYWORDS",DH."REQUESTOR_NAME",DH."REQUESTOR_ORG",DH."REQUESTOR_PHONE",DH."REQUESTOR_EMAIL",DH."RECEIVER",DH."RECEIVER_EMAIL",DH."SME",DH."SME_ASSIGNED_DATE",DH."RESOLVED_DATE",DH."REQUEST_DISPLAY_ID",DH."VALIDATION_SME",DH."ASSIGNED_TO_VALIDATOR",DH."VALIDATION_DATE",DH."CLOSED_DATE",DH."MODIFIED_DATE",DH."PII_FLAG",DH."REQUEST_PURPOSE",DH."SPEC_CONSIDERATIONS",DH."REQUEST_DESCR",DH."COMMENTS",DH."TRACKING_SUFFIX",DH."TRACKING_NUMBER",DH."SYSTEM_NAME",DH."DELAY_REASON",DH."ORIGINAL_REQUEST_DATE",DH."AGREED_DUE_DATE",DH."ANTICIPATED_DUE_DATE",DH."DATE_RUN",DH."REPORT_TYPE",DH."QUERY_REPORT_NAME",DH."CLARIF_ASSUMPS",DH."DETAIL_STEPS",DH."VALIDATION_DESCR",DH."VALIDATION_RESULT",DH."GOLDEN_QUERY_LIBRARY",DH."BUSINESS_REQS",DH."TIER",DH."SME_GROUP",DH."VALIDATION_SME_GROUP", RUT.ID_ AS CURRENT_TASK_ID, RUT.NAME_ AS CURRENT_TASK_NAME, RUT.FORM_KEY_ AS CURRENT_TASK_FORM_KEY FROM DRTS_HISTORY DH
LEFT JOIN ACT_RU_TASK  RUT on DH.PROC_INST_ID_ = RUT.PROC_INST_ID_;
