//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package gov.ed.fsa.drts.aimsdrts;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.ed.fsa.drts.aimsdrts package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DeleteAccountResponse_QNAME = new QName("http://drts.fsa.ed.gov/AimsDrts", "DeleteAccountResponse");
    private final static QName _CreateAccountResponse_QNAME = new QName("http://drts.fsa.ed.gov/AimsDrts", "CreateAccountResponse");
    private final static QName _DeleteAccountRequest_QNAME = new QName("http://drts.fsa.ed.gov/AimsDrts", "DeleteAccountRequest");
    private final static QName _CreateAccountRequest_QNAME = new QName("http://drts.fsa.ed.gov/AimsDrts", "CreateAccountRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.ed.fsa.drts.aimsdrts
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateAccountRequestType }
     * 
     */
    public CreateAccountRequestType createCreateAccountRequestType() {
        return new CreateAccountRequestType();
    }

    /**
     * Create an instance of {@link CreateAccountResponseType }
     * 
     */
    public CreateAccountResponseType createCreateAccountResponseType() {
        return new CreateAccountResponseType();
    }

    /**
     * Create an instance of {@link DeleteAccountResponseType }
     * 
     */
    public DeleteAccountResponseType createDeleteAccountResponseType() {
        return new DeleteAccountResponseType();
    }

    /**
     * Create an instance of {@link DeleteAccountRequestType }
     * 
     */
    public DeleteAccountRequestType createDeleteAccountRequestType() {
        return new DeleteAccountRequestType();
    }

    /**
     * Create an instance of {@link CommonResponseType }
     * 
     */
    public CommonResponseType createCommonResponseType() {
        return new CommonResponseType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteAccountResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://drts.fsa.ed.gov/AimsDrts", name = "DeleteAccountResponse")
    public JAXBElement<DeleteAccountResponseType> createDeleteAccountResponse(DeleteAccountResponseType value) {
        return new JAXBElement<DeleteAccountResponseType>(_DeleteAccountResponse_QNAME, DeleteAccountResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateAccountResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://drts.fsa.ed.gov/AimsDrts", name = "CreateAccountResponse")
    public JAXBElement<CreateAccountResponseType> createCreateAccountResponse(CreateAccountResponseType value) {
        return new JAXBElement<CreateAccountResponseType>(_CreateAccountResponse_QNAME, CreateAccountResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteAccountRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://drts.fsa.ed.gov/AimsDrts", name = "DeleteAccountRequest")
    public JAXBElement<DeleteAccountRequestType> createDeleteAccountRequest(DeleteAccountRequestType value) {
        return new JAXBElement<DeleteAccountRequestType>(_DeleteAccountRequest_QNAME, DeleteAccountRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateAccountRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://drts.fsa.ed.gov/AimsDrts", name = "CreateAccountRequest")
    public JAXBElement<CreateAccountRequestType> createCreateAccountRequest(CreateAccountRequestType value) {
        return new JAXBElement<CreateAccountRequestType>(_CreateAccountRequest_QNAME, CreateAccountRequestType.class, null, value);
    }

}
