--------------------------------------------------------
--  File created - Wednesday-January-25-2017   
--------------------------------------------------------
DROP TABLE "DRTS_ATTACHMENTS";
DROP TABLE "DRTS_AUDIT";
DROP TABLE "DRTS_HISTORY";
DROP TABLE "DRTS_ITERATIONS";
DROP TABLE "DRTS_VIEW_COMMENTS_PERMISSION";
--------------------------------------------------------
--  DDL for Table DRTS_ATTACHMENTS
--------------------------------------------------------

  CREATE TABLE "DRTS_ATTACHMENTS" ("REQUEST_ID" VARCHAR2(256), "FILE_TYPE" VARCHAR2(256), "FILE_NAME" VARCHAR2(256), "FILE_CONTENT" BLOB, "FILE_SIZE" NUMBER, "ID" VARCHAR2(256 CHAR)) ;
--------------------------------------------------------
--  DDL for Table DRTS_AUDIT
--------------------------------------------------------

  CREATE TABLE "DRTS_AUDIT" ("AUDIT_ID" NVARCHAR2(256), "REQUEST_NUMBER" NVARCHAR2(256), "FIELD_NAME" NVARCHAR2(256), "OLD_VALUE" NVARCHAR2(256), "NEW_VALUE" NVARCHAR2(256), "MODIFIED_DATE" TIMESTAMP (6), "MODIFIED_BY" NVARCHAR2(256)) ;
--------------------------------------------------------
--  DDL for Table DRTS_HISTORY
--------------------------------------------------------

  CREATE TABLE "DRTS_HISTORY" ("REQUEST_NUMBER" NVARCHAR2(256), "DRT_REQUEST_DATE" TIMESTAMP (6), "PROC_INST_ID_" NVARCHAR2(64), "CANDIDATE_GROUP" NVARCHAR2(256), "ASSIGNEE" NVARCHAR2(256), "REQUEST_TYPE" NVARCHAR2(256), "REQUEST_STATUS" NVARCHAR2(256), "CREATED_BY" NVARCHAR2(256), "ITERATION" NUMBER(19,0), "REQUESTED_DUE_DATE" DATE, "URGENCY_FLAG" NVARCHAR2(256), "RELATED_REQUEST_NUMBERS" NVARCHAR2(256), "TOPIC_KEYWORDS" NVARCHAR2(256), "REQUESTOR_NAME" NVARCHAR2(256), "REQUESTOR_ORG" NVARCHAR2(256), "REQUESTOR_PHONE" NVARCHAR2(256), "REQUESTOR_EMAIL" NVARCHAR2(256), "RECEIVER" NVARCHAR2(256), "RECEIVER_EMAIL" NVARCHAR2(256), "SME" NVARCHAR2(256), "SME_ASSIGNED_DATE" DATE, "RESOLVED_DATE" DATE, "REQUEST_DISPLAY_ID" NUMBER, "VALIDATION_SME" NVARCHAR2(256), "ASSIGNED_TO_VALIDATOR" DATE, "VALIDATION_DATE" DATE, "CLOSED_DATE" TIMESTAMP (6), "MODIFIED_DATE" TIMESTAMP (6), "PII_FLAG" NUMBER(1,0), "REQUEST_PURPOSE" NCLOB, "SPEC_CONSIDERATIONS" NCLOB, "REQUEST_DESCR" NCLOB, "COMMENTS" NCLOB, "TRACKING_SUFFIX" NCHAR(1), "TRACKING_NUMBER" NVARCHAR2(293), "SYSTEM_NAME" NVARCHAR2(256), "DELAY_REASON" NVARCHAR2(256), "ORIGINAL_REQUEST_DATE" DATE, "AGREED_DUE_DATE" DATE, "ANTICIPATED_DUE_DATE" DATE, "DATE_RUN" DATE, "REPORT_TYPE" NVARCHAR2(256), "QUERY_REPORT_NAME" NVARCHAR2(256), "CLARIF_ASSUMPS" NCLOB, "DETAIL_STEPS" NCLOB, "VALIDATION_DESCR" NCLOB, "VALIDATION_RESULT" NCLOB, "GOLDEN_QUERY_LIBRARY" NCLOB, "BUSINESS_REQS" NVARCHAR2(2000), "TIER" NUMBER(19,0), "SME_GROUP" NVARCHAR2(256), "VALIDATION_SME_GROUP" NVARCHAR2(256), "MODIFIED_BY" NVARCHAR2(256)) ;
--------------------------------------------------------
--  DDL for Table DRTS_ITERATIONS
--------------------------------------------------------

  CREATE TABLE "DRTS_ITERATIONS" ("PARENT_ID" VARCHAR2(256), "ITERATION" NUMBER, "CHILD_ID" VARCHAR2(256)) ;
--------------------------------------------------------
--  DDL for Table DRTS_VIEW_COMMENTS_PERMISSION
--------------------------------------------------------

  CREATE TABLE "DRTS_VIEW_COMMENTS_PERMISSION" ("REQUEST_NUMBER" NVARCHAR2(256)) ;
--------------------------------------------------------
--  DDL for Index DRTS_ATTACHMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DRTS_ATTACHMENTS_PK" ON "DRTS_ATTACHMENTS" ("ID") ;
--------------------------------------------------------
--  DDL for Index DRTS_HISTORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DRTS_HISTORY_PK" ON "DRTS_HISTORY" ("REQUEST_NUMBER") ;
--------------------------------------------------------
--  DDL for Index DRTS_ITERATIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DRTS_ITERATIONS_PK" ON "DRTS_ITERATIONS" ("PARENT_ID", "ITERATION") ;
--------------------------------------------------------
--  DDL for Index DRTS_VIEW_COMMENTS_PERM_IDX1
--------------------------------------------------------

  CREATE INDEX "DRTS_VIEW_COMMENTS_PERM_IDX1" ON "DRTS_VIEW_COMMENTS_PERMISSION" ("REQUEST_NUMBER") ;
--------------------------------------------------------
--  Constraints for Table DRTS_ATTACHMENTS
--------------------------------------------------------

  ALTER TABLE "DRTS_ATTACHMENTS" ADD CONSTRAINT "DRTS_ATTACHMENTS_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "DRTS_ATTACHMENTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DRTS_ATTACHMENTS" MODIFY ("FILE_SIZE" NOT NULL ENABLE);
  ALTER TABLE "DRTS_ATTACHMENTS" MODIFY ("FILE_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "DRTS_ATTACHMENTS" MODIFY ("FILE_NAME" NOT NULL ENABLE);
  ALTER TABLE "DRTS_ATTACHMENTS" MODIFY ("FILE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "DRTS_ATTACHMENTS" MODIFY ("REQUEST_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DRTS_AUDIT
--------------------------------------------------------

  ALTER TABLE "DRTS_AUDIT" MODIFY ("REQUEST_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "DRTS_AUDIT" MODIFY ("AUDIT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DRTS_HISTORY
--------------------------------------------------------

  ALTER TABLE "DRTS_HISTORY" ADD CONSTRAINT "DRTS_HISTORY_PK" PRIMARY KEY ("REQUEST_NUMBER") ENABLE;
  ALTER TABLE "DRTS_HISTORY" MODIFY ("DRT_REQUEST_DATE" NOT NULL ENABLE);
  ALTER TABLE "DRTS_HISTORY" MODIFY ("REQUEST_NUMBER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DRTS_ITERATIONS
--------------------------------------------------------

  ALTER TABLE "DRTS_ITERATIONS" ADD CONSTRAINT "DRTS_ITERATIONS_PK" PRIMARY KEY ("PARENT_ID", "ITERATION") ENABLE;
  ALTER TABLE "DRTS_ITERATIONS" MODIFY ("CHILD_ID" NOT NULL ENABLE);
  ALTER TABLE "DRTS_ITERATIONS" MODIFY ("ITERATION" NOT NULL ENABLE);
  ALTER TABLE "DRTS_ITERATIONS" MODIFY ("PARENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DRTS_VIEW_COMMENTS_PERMISSION
--------------------------------------------------------

  ALTER TABLE "DRTS_VIEW_COMMENTS_PERMISSION" ADD CONSTRAINT "DRTS_VIEW_COMMENTS_PERMISS_PK" PRIMARY KEY ("REQUEST_NUMBER") ENABLE;
  ALTER TABLE "DRTS_VIEW_COMMENTS_PERMISSION" MODIFY ("REQUEST_NUMBER" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table DRTS_VIEW_COMMENTS_PERMISSION
--------------------------------------------------------

  ALTER TABLE "DRTS_VIEW_COMMENTS_PERMISSION" ADD CONSTRAINT "DRTS_VIEW_COMMENTS_PERMIS_FK1" FOREIGN KEY ("REQUEST_NUMBER") REFERENCES "DRTS_HISTORY" ("REQUEST_NUMBER") ON DELETE CASCADE ENABLE;
