//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package gov.ed.fsa.drts.aimsdrtsservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import gov.ed.fsa.drts.aimsdrts.CreateAccountRequestType;
import gov.ed.fsa.drts.aimsdrts.CreateAccountResponseType;
import gov.ed.fsa.drts.aimsdrts.DeleteAccountRequestType;
import gov.ed.fsa.drts.aimsdrts.DeleteAccountResponseType;
import gov.ed.fsa.drts.aimsdrts.ObjectFactory;

@WebService(name = "AimsDrtsService", targetNamespace = "http://drts.fsa.ed.gov/AimsDrtsService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AimsDrtsService {


    /**
     * 
     * @param createAccountRequest
     * @return
     *     returns gov.ed.fsa.drts.aimsdrts.CreateAccountResponseType
     */
    @WebMethod(operationName = "CreateAccount", action = "http://aims.fsa.ed.gov/AimsDrtsService/CreateAccount")
    @WebResult(name = "CreateAccountResponse", targetNamespace = "http://drts.fsa.ed.gov/AimsDrts", partName = "CreateAccountResponse")
    public CreateAccountResponseType createAccount(
        @WebParam(name = "CreateAccountRequest", targetNamespace = "http://drts.fsa.ed.gov/AimsDrts", partName = "CreateAccountRequest")
        CreateAccountRequestType createAccountRequest);

    /**
     * 
     * @param deleteAccountRequest
     * @return
     *     returns gov.ed.fsa.drts.aimsdrts.DeleteAccountResponseType
     */
    @WebMethod(operationName = "DeleteAccount", action = "http://aims.fsa.ed.gov/AimsDrtsService/DeleteAccount")
    @WebResult(name = "DeleteAccountResponse", targetNamespace = "http://drts.fsa.ed.gov/AimsDrts", partName = "DeleteAccountResponse")
    public DeleteAccountResponseType deleteAccount(
        @WebParam(name = "DeleteAccountRequest", targetNamespace = "http://drts.fsa.ed.gov/AimsDrts", partName = "DeleteAccountRequest")
        DeleteAccountRequestType deleteAccountRequest);

}
